#!/usr/bin/env bash
# Folds content/knowledge.js and the widget into the two files you paste into
# Wix. Run it after editing either one.
#
#   embed/chat.html        -> Wix "Embed HTML" element (option A in README.md)
#   embed/ai-chat.velo.js  -> Velo public/custom-elements file (option B)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
widget="$here/public/custom-elements/ai-chat.js"
knowledge="$here/content/knowledge.js"

mkdir -p "$here/embed"

{
  cat "$here/embed/_head.html"
  cat "$knowledge"
  cat "$widget"
  cat "$here/embed/_tail.html"
} > "$here/embed/chat.html"

{
  echo "/* Generated by build.sh from content/knowledge.js + public/custom-elements/ai-chat.js."
  echo "   Paste this file into Wix as public/custom-elements/ai-chat.js. Edit the"
  echo "   two source files instead of this one. */"
  cat "$knowledge"
  cat "$widget"
} > "$here/embed/ai-chat.velo.js"

for f in "$here/embed/chat.html" "$here/embed/ai-chat.velo.js"; do
  echo "wrote $f ($(wc -c < "$f" | tr -d ' ') bytes)"
done
