/* Generated by build.sh from content/knowledge.js + public/custom-elements/ai-chat.js.
   Paste this file into Wix as public/custom-elements/ai-chat.js. Edit the
   two source files instead of this one. */
/**
 * What the assistant knows about your site.
 *
 * This is the only file you edit to change the answers. build.sh folds it into
 * embed/chat.html and embed/ai-chat.velo.js, so both ways of putting the widget
 * on a Wix page pick it up with no further steps.
 *
 * Write plain sentences, the way you would answer a customer. Keep each entry
 * to one subject and give it a title that names that subject, because the title
 * is what gets matched when there is too much content to send at once.
 *
 * Replace everything below with your own business. The studio is made up.
 */
window.AI_CHAT_KNOWLEDGE = [
  {
    title: "What Northwind Studio does",
    text:
      "Northwind Studio is a portrait and product photography studio in " +
      "Portland, Oregon. We shoot headshots for individuals and teams, " +
      "product photography for online shops, and small events. We do not " +
      "shoot weddings.",
  },
  {
    title: "Prices and packages",
    text:
      "A single headshot session is $180 and includes three retouched " +
      "photos. Team headshots are $120 per person for groups of four or " +
      "more. Product photography starts at $40 per item, with a minimum of " +
      "ten items. Event coverage is $300 for the first two hours and $100 " +
      "for each hour after that.",
  },
  {
    title: "Opening hours",
    text:
      "The studio is open Tuesday to Saturday, 9am to 6pm. We are closed " +
      "Sunday and Monday. Evening sessions can be booked on request.",
  },
  {
    title: "How to book",
    text:
      "Book through the contact form on this site, or email " +
      "hello@northwindstudio.example. We usually reply within one business " +
      "day. A session is held once a 50% deposit is paid, and the deposit " +
      "is refundable up to 48 hours before the session.",
  },
  {
    title: "Where we are and parking",
    text:
      "The studio is at 118 NE Alberta Street, Portland. There is free " +
      "street parking on Alberta and a paid lot one block east. The nearest " +
      "bus stop is Alberta and NE 14th.",
  },
  {
    title: "Turnaround and delivery",
    text:
      "Edited photos arrive as a private online gallery within five business " +
      "days. Rush delivery in 48 hours costs an extra $75. You get full " +
      "rights to use the photos for your own business.",
  },
];
/**
 * <ai-chat> — a chat widget that runs the language model inside the visitor's
 * browser via WebLLM (https://github.com/mlc-ai/web-llm). No backend, no API
 * key, no per-message cost: the weights are downloaded once, cached by the
 * browser, and every token is generated on the visitor's GPU through WebGPU.
 *
 * This file is the single source of truth for the widget. It is used in two
 * places (see ../../README.md):
 *   - as a Wix custom element, from public/custom-elements/ai-chat.js
 *   - inlined into embed/chat.html by build.sh, for the Embed HTML element
 *
 * Attributes (all optional):
 *   model          WebLLM model id, e.g. "Qwen2.5-0.5B-Instruct-q4f16_1-MLC"
 *   system-prompt  instructions that shape the assistant's replies
 *   greeting       opening line shown to the visitor; display only, and never
 *                  sent to the model (see _showGreeting)
 *   heading        label in the widget header
 */
(function () {
  "use strict";

  if (customElements.get("ai-chat")) return;

  var WEBLLM_ESM = "https://esm.run/@mlc-ai/web-llm@0.2.85";
  var DEFAULT_MODEL = "Llama-3.2-1B-Instruct-q4f16_1-MLC";
  var DEFAULT_SYSTEM =
    "You are an assistant on a business's website. Answer the user's " +
    "question directly and concretely. Do not repeat yourself, do not use " +
    "filler pleasantries, and do not ask what is on the user's mind. Keep " +
    "answers under three sentences unless asked for more.";

  // Wrapped around the site content before it is handed to the model. The
  // models this widget runs are small enough that they invent business
  // details when asked, so they are told to answer from the text or not at all.
  var GROUNDING =
    "Answer using only the information about this business given below. If " +
    "the answer is not in it, say you do not have that information and " +
    "suggest getting in touch through the site. Never invent prices, hours, " +
    "addresses, links or policies.";

  // Characters of site content sent with a question. The models have a 4096
  // token window, and this leaves room for the conversation and the answer.
  // Content under this size is sent whole; above it, the entries closest to
  // the question are picked.
  var KNOWLEDGE_BUDGET = 6000;

  // Shown instead of an answer that invented a way to contact the business.
  var WITHHELD =
    "I don't have that detail. Please use the contact details on this site.";

  // Contact details are the one class of invention that can be checked rather
  // than discouraged. The model has no legitimate source for a phone number,
  // email or link that is not in the site content, so anything of that shape
  // which does not appear there was made up. Measured: Qwen2.5-0.5B invented a
  // phone number under every system prompt tried, and Llama-3.2-1B invented a
  // named employee. Wording alone does not stop it.
  var CONTACT_PATTERNS = [
    { kind: "email", re: /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi },
    { kind: "link", re: /\b(?:https?:\/\/|www\.)[^\s<>"')\]]+/gi },
    { kind: "phone", re: /\+?\d[\d\s().-]{6,}\d/g },
  ];

  var STOPWORDS = {
    a: 1, an: 1, and: 1, are: 1, as: 1, at: 1, be: 1, but: 1, by: 1, can: 1,
    did: 1, do: 1, does: 1, for: 1, from: 1, get: 1, give: 1, has: 1, have: 1,
    how: 1, i: 1, in: 1, is: 1, it: 1, me: 1, much: 1, my: 1, of: 1, on: 1,
    or: 1, that: 1, the: 1, there: 1, they: 1, this: 1, to: 1, was: 1, we: 1,
    what: 1, when: 1, where: 1, which: 1, who: 1, why: 1, will: 1, with: 1,
    you: 1, your: 1,
  };

  // Small models fall into a loop and answer every prompt with the same
  // sentence unless new tokens are rewarded. Measured on SmolLM2-360M,
  // Qwen2.5-0.5B and Llama-3.2-1B: without these, asking the same question
  // twice returns character-for-character identical text.
  var GENERATION = {
    temperature: 0.7,
    frequency_penalty: 0.6,
    presence_penalty: 0.6,
    repetition_penalty: 1.1,
  };

  // Turns of history sent to the model, not counting the system prompt. The
  // supported models have a 4096 token context window, which a long chat
  // would otherwise overrun.
  var MAX_HISTORY = 12;

  // One-time download per visitor, in MB, measured from the mlc-ai model repos
  // on Hugging Face. Used only to set expectations before the download starts.
  var DOWNLOAD_MB = {
    "SmolLM2-360M-Instruct-q4f16_1-MLC": 210,
    "Qwen2.5-0.5B-Instruct-q4f16_1-MLC": 290,
    "gemma3-1b-it-q4f16_1-MLC": 530,
    "Llama-3.2-1B-Instruct-q4f16_1-MLC": 700,
    "Llama-3.2-1B-Instruct-q4f32_1-MLC": 950,
    "Qwen2.5-1.5B-Instruct-q4f16_1-MLC": 1100,
  };

  // Set by content/knowledge.js, which build.sh places ahead of this file.
  function knowledgeChunks() {
    var raw = (typeof window !== "undefined" && window.AI_CHAT_KNOWLEDGE) || [];
    if (!Array.isArray(raw)) return [];
    return raw.filter(function (c) { return c && c.text; });
  }

  function keywords(text) {
    var words = String(text).toLowerCase().match(/[a-z0-9']+/g) || [];
    var out = {};
    for (var i = 0; i < words.length; i++) {
      if (words[i].length > 2 && !STOPWORDS[words[i]]) out[words[i]] = true;
    }
    return Object.keys(out);
  }

  // How well one entry answers the question: how many of the question's words
  // it contains, with a word in the title counting double.
  function relevance(chunk, question) {
    var asked = keywords(question);
    if (!asked.length) return 0;
    var title = " " + String(chunk.title || "").toLowerCase() + " ";
    var body = " " + String(chunk.text).toLowerCase() + " ";
    var score = 0;
    for (var i = 0; i < asked.length; i++) {
      if (title.indexOf(asked[i]) !== -1) score += 2;
      else if (body.indexOf(asked[i]) !== -1) score += 1;
    }
    return score;
  }

  function digitsOf(text) {
    return String(text).replace(/\D+/g, "");
  }

  // Returns the first contact detail in the answer that is absent from the
  // site content, or null when every one of them checks out.
  function inventedContactDetail(answer, source) {
    var haystack = String(source).toLowerCase();
    var sourceDigits = digitsOf(source);
    for (var i = 0; i < CONTACT_PATTERNS.length; i++) {
      var pattern = CONTACT_PATTERNS[i];
      pattern.re.lastIndex = 0;
      var match;
      while ((match = pattern.re.exec(answer)) !== null) {
        var token = match[0];
        if (pattern.kind === "phone") {
          var digits = digitsOf(token);
          if (digits.length >= 7 && sourceDigits.indexOf(digits) === -1) return token;
        } else if (haystack.indexOf(token.toLowerCase()) === -1) {
          return token;
        }
      }
    }
    return null;
  }

  function renderChunks(chunks) {
    return chunks.map(function (c) {
      return (c.title ? c.title + "\n" : "") + c.text;
    }).join("\n\n");
  }

  var CSS = [
    ':host{display:block;height:100%;min-height:320px;',
    '--bg:#ffffff;--fg:#1a1c1f;--muted:#6b7280;--line:#e5e7eb;',
    '--accent:#2b6cb0;--accent-fg:#ffffff;--bubble:#f3f4f6;',
    "font-family:inherit;color:var(--fg)}",
    '@media (prefers-color-scheme:dark){:host{--bg:#16181c;--fg:#e8eaed;',
    '--muted:#9aa0a6;--line:#2a2e35;--bubble:#22262d}}',
    '*{box-sizing:border-box}',
    '.wrap{display:flex;flex-direction:column;height:100%;background:var(--bg);',
    'border:1px solid var(--line);border-radius:12px;overflow:hidden}',
    '.bar{display:flex;align-items:center;gap:8px;padding:10px 14px;',
    'border-bottom:1px solid var(--line);font-size:14px;font-weight:600}',
    '.dot{width:8px;height:8px;border-radius:50%;background:var(--muted);flex:none}',
    '.dot[data-state="loading"]{background:#d97706;animation:pulse 1.2s infinite}',
    '.dot[data-state="ready"]{background:#16a34a}',
    '.dot[data-state="error"]{background:#dc2626}',
    '@keyframes pulse{50%{opacity:.35}}',
    '.bar .spacer{flex:1}',
    '.ghost{border:0;background:none;color:var(--muted);font:inherit;font-size:13px;',
    'cursor:pointer;padding:4px 6px;border-radius:6px}',
    '.ghost:hover{color:var(--fg);background:var(--bubble)}',
    '.log{flex:1;overflow-y:auto;padding:14px;display:flex;flex-direction:column;gap:10px}',
    '.msg{max-width:85%;padding:9px 12px;border-radius:14px;font-size:14px;',
    'line-height:1.5;white-space:pre-wrap;word-wrap:break-word}',
    '.msg.user{align-self:flex-end;background:var(--accent);color:var(--accent-fg);',
    'border-bottom-right-radius:4px}',
    '.msg.bot{align-self:flex-start;background:var(--bubble);border-bottom-left-radius:4px}',
    '.msg.bot.pending::after{content:"▍";opacity:.5}',
    '.msg.err{color:#dc2626}',
    '.msg.withheld{font-style:italic;color:var(--muted)}',
    '.gate{padding:20px 16px;text-align:center;display:flex;flex-direction:column;',
    'align-items:center;gap:10px;margin:auto}',
    '.gate p{margin:0;font-size:13px;color:var(--muted);line-height:1.5;max-width:44ch}',
    '.gate .err{color:#dc2626}',
    'button.primary{border:0;border-radius:999px;background:var(--accent);',
    'color:var(--accent-fg);font:inherit;font-size:14px;font-weight:600;',
    'padding:10px 20px;cursor:pointer}',
    'button.primary:hover{filter:brightness(1.08)}',
    'button:disabled{opacity:.55;cursor:default;filter:none}',
    '.track{width:100%;max-width:280px;height:5px;border-radius:999px;',
    'background:var(--bubble);overflow:hidden}',
    '.track>i{display:block;height:100%;width:0;background:var(--accent);',
    'transition:width .25s ease}',
    '.composer{display:flex;gap:8px;padding:10px;border-top:1px solid var(--line);',
    'align-items:flex-end}',
    'textarea{flex:1;resize:none;max-height:120px;border:1px solid var(--line);',
    'border-radius:10px;padding:9px 11px;font:inherit;font-size:14px;',
    'background:var(--bg);color:var(--fg)}',
    'textarea:focus{outline:2px solid var(--accent);outline-offset:-1px}',
    '.foot{margin:0;padding:0 14px 8px;font-size:11px;color:var(--muted);text-align:center}',
    '[hidden]{display:none!important}',
  ].join("");

  var HTML = [
    '<div class="wrap">',
    '  <div class="bar"><span class="dot" id="dot"></span><span id="title"></span>',
    '    <span class="spacer"></span>',
    '    <button class="ghost" id="clear" hidden>Clear</button></div>',
    '  <div class="log" id="log" role="log" aria-live="polite" aria-atomic="false"></div>',
    '  <div class="gate" id="gate">',
    '    <p id="gateText"></p>',
    '    <div class="track" id="track" hidden><i id="bar"></i></div>',
    '    <button class="primary" id="start">Start the chat</button>',
    '  </div>',
    '  <form class="composer" id="composer" hidden>',
    '    <textarea id="input" rows="1" aria-label="Message"></textarea>',
    '    <button class="primary" id="send" type="submit">Send</button>',
    '    <button class="primary" id="stop" type="button" hidden>Stop</button>',
    '  </form>',
    '  <p class="foot" id="foot"></p>',
    '</div>',
  ].join("\n");

  class AiChat extends HTMLElement {
    constructor() {
      super();
      this._engine = null;
      this._busy = false;
      this._history = [];
      this.attachShadow({ mode: "open" });
    }

    get model() {
      return this.getAttribute("model") || DEFAULT_MODEL;
    }

    get systemPrompt() {
      return this.getAttribute("system-prompt") || DEFAULT_SYSTEM;
    }

    connectedCallback() {
      if (this._built) return;
      this._built = true;

      var style = document.createElement("style");
      style.textContent = CSS;
      this.shadowRoot.appendChild(style);
      var host = document.createElement("div");
      host.innerHTML = HTML;
      this.shadowRoot.appendChild(host);

      var $ = this.shadowRoot.getElementById.bind(this.shadowRoot);
      this._el = {
        dot: $("dot"), title: $("title"), clear: $("clear"), log: $("log"),
        gate: $("gate"), gateText: $("gateText"), track: $("track"), bar: $("bar"),
        start: $("start"), composer: $("composer"), input: $("input"),
        send: $("send"), stop: $("stop"), foot: $("foot"),
      };

      this._el.title.textContent = this.getAttribute("heading") || "Ask me anything";

      // The greeting is shown but deliberately kept out of _history. An
      // assistant turn before the user has said anything makes small models
      // answer every later prompt with a variation of that greeting.
      this._showGreeting();

      this._el.start.addEventListener("click", this._load.bind(this));
      this._el.composer.addEventListener("submit", this._submit.bind(this));
      this._el.clear.addEventListener("click", this._clear.bind(this));
      this._el.stop.addEventListener("click", this._interrupt.bind(this));
      this._el.input.addEventListener("keydown", function (e) {
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          this._el.composer.requestSubmit();
        }
      }.bind(this));
      this._el.input.addEventListener("input", this._autogrow.bind(this));

      this._describeDownload();
    }

    _describeDownload() {
      if (!this._webgpuAvailable()) {
        this._state("error");
        this._el.gateText.className = "err";
        this._el.gateText.textContent =
          "This chat needs WebGPU, which this browser does not expose. " +
          "It works in a recent Chrome or Edge, or in Safari 26 and later.";
        this._el.start.hidden = true;
        return;
      }
      var mb = DOWNLOAD_MB[this.model];
      this._el.gateText.textContent =
        "The assistant runs entirely in your browser. The first start downloads " +
        (mb ? "about " + (mb >= 1000 ? (mb / 1000).toFixed(1) + " GB" : mb + " MB") : "the model") +
        " of model weights, which your browser then caches. Nothing you type leaves this device.";
    }

    _webgpuAvailable() {
      try {
        return typeof navigator !== "undefined" && !!navigator.gpu;
      } catch (e) {
        return false;
      }
    }

    async _load() {
      var el = this._el;
      el.start.disabled = true;
      el.track.hidden = false;
      this._state("loading");

      try {
        var webllm = await import(/* webpackIgnore: true */ WEBLLM_ESM);
        this._engine = await webllm.CreateMLCEngine(this.model, {
          initProgressCallback: function (report) {
            el.bar.style.width = Math.round((report.progress || 0) * 100) + "%";
            el.gateText.textContent = report.text || "Loading…";
          },
        });
      } catch (err) {
        this._state("error");
        el.track.hidden = true;
        el.start.disabled = false;
        el.start.textContent = "Try again";
        el.gateText.className = "err";
        el.gateText.textContent = "Could not load the model: " + this._reason(err);
        return;
      }

      this._state("ready");
      el.gate.hidden = true;
      el.composer.hidden = false;
      el.clear.hidden = false;
      el.foot.textContent = this.model + " · running locally · answers can be wrong";
      el.input.focus();
    }

    async _submit(event) {
      event.preventDefault();
      if (this._busy || !this._engine) return;

      var text = this._el.input.value.trim();
      if (!text) return;

      this._el.input.value = "";
      this._autogrow();
      this._bubble("user").textContent = text;
      this._history.push({ role: "user", content: text });

      var bubble = this._bubble("bot");
      bubble.classList.add("pending");
      this._setBusy(true);

      var answer = "";
      try {
        var request = {
          messages: this._messagesFor(text),
          stream: true,
          stream_options: { include_usage: true },
        };
        for (var key in GENERATION) request[key] = GENERATION[key];
        var stream = await this._engine.chat.completions.create(request);
        for await (var chunk of stream) {
          var delta = chunk.choices[0] && chunk.choices[0].delta.content;
          if (delta) {
            answer += delta;
            bubble.textContent = answer;
            this._scroll();
          }
          if (chunk.usage && chunk.usage.extra) {
            this._el.foot.textContent =
              this.model + " · " +
              Math.round(chunk.usage.extra.decode_tokens_per_s) +
              " tokens/sec locally · answers can be wrong";
          }
        }
      } catch (err) {
        bubble.classList.add("err");
        answer = answer || "Sorry, that response failed: " + this._reason(err);
        bubble.textContent = answer;
      }

      bubble.classList.remove("pending");

      var invented = this._inventedDetail(answer);
      if (invented) {
        answer = WITHHELD;
        bubble.textContent = answer;
        bubble.classList.add("withheld");
      }

      this._history.push({ role: "assistant", content: answer });
      this._setBusy(false);
      this._el.input.focus();
    }

    _interrupt() {
      if (this._engine && this._busy) this._engine.interruptGenerate();
    }

    async _clear() {
      if (this._busy) return;
      this._el.log.innerHTML = "";
      this._history = [];
      this._showGreeting();
      if (this._engine) await this._engine.resetChat();
      this._el.input.focus();
    }

    // Only meaningful when the widget has site content: without it there is
    // nothing to check a phone number or link against, and a general chat is
    // entitled to mention addresses it knows.
    _inventedDetail(answer) {
      var chunks = knowledgeChunks();
      if (!chunks.length) return null;
      return inventedContactDetail(answer, renderChunks(chunks));
    }

    _showGreeting() {
      var greeting = this.getAttribute("greeting");
      if (greeting) this._bubble("bot").textContent = greeting;
    }

    // The system message is rebuilt for every question, because which site
    // content it carries depends on what was asked.
    _messagesFor(question) {
      var turns = this._history.length > MAX_HISTORY
        ? this._history.slice(-MAX_HISTORY)
        : this._history;
      return [{ role: "system", content: this._systemMessage(question) }].concat(turns);
    }

    _systemMessage(question) {
      var content = this._contextFor(question);
      if (!content) return this.systemPrompt;
      return this.systemPrompt + "\n\n" + GROUNDING + "\n\n" + content;
    }

    // Small sites fit whole, and sending everything beats picking wrongly.
    // Larger ones fall back to the entries that match the question, taken
    // best first until the budget is used up.
    _contextFor(question) {
      var chunks = knowledgeChunks();
      if (!chunks.length) return "";

      var whole = renderChunks(chunks);
      if (whole.length <= KNOWLEDGE_BUDGET) return whole;

      var ranked = chunks.slice().map(function (c, i) {
        return { chunk: c, score: relevance(c, question), order: i };
      }).sort(function (a, b) {
        return b.score - a.score || a.order - b.order;
      });

      var picked = [];
      var used = 0;
      for (var i = 0; i < ranked.length; i++) {
        var size = ranked[i].chunk.text.length + 40;
        if (used + size > KNOWLEDGE_BUDGET) continue;
        picked.push(ranked[i]);
        used += size;
      }
      picked.sort(function (a, b) { return a.order - b.order; });
      return renderChunks(picked.map(function (r) { return r.chunk; }));
    }

    _bubble(who) {
      var div = document.createElement("div");
      div.className = "msg " + who;
      this._el.log.appendChild(div);
      this._scroll();
      return div;
    }

    _scroll() {
      this._el.log.scrollTop = this._el.log.scrollHeight;
    }

    _autogrow() {
      var t = this._el.input;
      t.style.height = "auto";
      t.style.height = Math.min(t.scrollHeight, 120) + "px";
    }

    _setBusy(busy) {
      this._busy = busy;
      this._el.send.hidden = busy;
      this._el.stop.hidden = !busy;
      this._el.input.disabled = busy;
    }

    _state(state) {
      this._el.dot.setAttribute("data-state", state);
    }

    _reason(err) {
      var message = (err && (err.message || String(err))) || "unknown error";
      return message.length > 220 ? message.slice(0, 220) + "…" : message;
    }
  }

  customElements.define("ai-chat", AiChat);
})();
