#!/usr/bin/env bash
# Compiles the Jaspr app and folds it into the two things a Wix page can
# take. Run it after editing lib/knowledge.dart or anything else in lib/.
#
#   embed/chat.html   one file, everything inlined -> Wix "Embed HTML"
#   embed/site/       four files -> any static host, then "Embed a site"
#
# See README.md for which of the two to use.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/build/jaspr"
embed="$here/embed"

cd "$here"
jaspr build

# `jaspr build` leaves build-runner's own files in build/jaspr/packages.
# Nothing the page loads refers to them, so only these four are the site.
mkdir -p "$embed/site"
for f in index.html styles.css web_llm.js main.client.dart.js; do
  cp "$out/$f" "$embed/site/$f"
done

# A string holding "</script>" ends the enclosing script tag when it is
# inlined, whatever it means to JavaScript. One of package:genui's error
# messages contains one. Backslash-escaping the slash leaves the string
# identical to JavaScript and invisible to the HTML parser.
inline_js() {
  sed 's|</script|<\\/script|g' "$1"
}

{
  cat <<'HTML'
<!doctype html>
<!--
  Generated by build.sh — edit the Dart in lib/ instead.

  Paste this whole file into the Wix "Embed HTML" element
  (Add Elements > Embed Code > Popular Embeds > Embed HTML > Enter Code).

  Everything the chat needs is in here except the model itself, which the
  visitor's browser fetches from the Hugging Face CDN on first use and then
  caches.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ask me anything</title>
<style>
HTML
  cat "$out/styles.css"
  cat <<'HTML'
</style>
</head>
<body>
<script type="module">
HTML
  inline_js "$out/web_llm.js"
  cat <<'HTML'
</script>
<script>
HTML
  inline_js "$out/main.client.dart.js"
  cat <<'HTML'
</script>
</body>
</html>
HTML
} > "$embed/chat.html"

echo
echo "wrote $embed/chat.html ($(wc -c < "$embed/chat.html" | tr -d ' ') bytes)"
echo "wrote $embed/site/ ($(cat "$embed"/site/* | wc -c | tr -d ' ') bytes in 4 files)"
